### PR TITLE
beautiful soup post processing exporters, testing and building

### PR DESCRIPTION
**Pull request by tonyfast**
on 10/25, i shared [a notebook] that explores html modifications to html notebook documents.
these changes support this document.

## todo

- [x] integrate beautiful soup into the library
- [x] integrate beautiful soup into the template
- [x] use hatch for the build/test system
- [x] `<main>`, `<article>` and `<section>`  tags defined for the notebooks, cells, and outputs respectively.
- [x] a test example that replaces prompts with `<aside>`s
- [x] fix ci

[a notebook]: https://nbviewer.org/github/tonyfast/tonyfast/blob/main/tonyfast/xxii/oct/2022-10-25-static-notebook-tags.ipynb

### CODE REVIEW

**Comment by tonyfast** [comment]
this pull request is probably in a good place for review.

we focus on being about the post process documents exported by `nbconvert`. this allows for remediations to be reversed engineered for manual tests. for future work, we'll create a system that codifies out learning in formal `jinja2` templates.
the test notebook demostrates the features by using the `nbconvert` apis interactively and at the command line.

please help with language too. im not confident in writing formal technical content.

**Comment by isabela-pf** [comment]
I gave this a look, but I think it's too far outside my knowledge base for me to review. Please let me know if there's any feedback you'd like me to give.

**Comment by smythp** [comment]
Going to pull it in and review. Will ikely have questions. :)

**Comment by tonyfast** [comment]
> Tony, pulled it in and got the tests running. (After taking a little while to realize I needed to reinstall the html5 module.)

hopefully the next pull doesn't require that. i changed the build system and should have been more transparent.

> This seems like a good basis to build on. I can't say I fully understand the invocation at the end (the command line command.) It seems you're adding the function written in the jupyter_nbconvert_config.py file to run at the end of the nbconvert process. It seems you're not passing a list of postprocess functions...how would you apply multiple transformations? Or is that a bad idea?

we can totally apply multiple transformations with either a change in the current configuration or encapsulating multiple functions in a one function.

> I'm going to merge this in. I'm pretty OK with BS4 as I do a lot of scraping, and might try creating a config file that does something different to see if I'm getting how the postprocessing works.

that would be great to know how malleable the interface is.

**Pull request merged**
